### ISSUE TITLE
DeployFailed.ps1 not automatically cleaned up after successful deployment

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#2052]

**Comment by antonvk** [comment]
Is there a date when this is expected to be resolved?

**Comment by tothegills** [comment]
DeployFailed.ps1 does not run when a deployment has failed.

**Comment by tothegills** [comment]
Release note: `DeployFailed.ps1` rollback convention will be run when a package fails to deploy

**Comment by vanessalove** [comment]
This was released in 3.1.6 - However there was a further issue where it was always being run regardless of deployment state. The second issue was corrected in 3.2.2 https://github.com/OctopusDeploy/Issues/issues/2135

**Comment by mihalios** [comment]
This is still an issue in v. 3.14.15.

DeployFailed.ps1 doesn't get removed.

**Comment by matt-richardson** [comment]
@mihalios, can you please get in touch via one of our [support channels](https://octopus.com/support)? That way we'll be able to look into it for you.

**Comment by johnsimons** [comment]
So it seems the reported issue is actually not fixed!
The fix released in https://github.com/OctopusDeploy/Issues/issues/2052#issuecomment-151718437, is actually referring to a different issue.

So, I have opened a [new issue](https://github.com/OctopusDeploy/Issues/issues/3608), to handle the original reported issue in here.
