### ISSUE TITLE
Deploy a release Deployment Condition cannot be bound to a variable

### ISSUE THREAD

**Issue by OctopusBob** [OctopusDeploy/Issues#5151]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

The deploy a release step has the ability to specify a deployment condition.  That feature appears as if it can be bound to a variable.

![image](https://user-images.githubusercontent.com/38642825/49607892-e0492e80-f95c-11e8-86c6-ff3109af8371.png)

If I choose the second option and click the binding link then the screen turns to this:

![image](https://user-images.githubusercontent.com/38642825/49607919-f951df80-f95c-11e8-8699-71fdf045e9c7.png)

If I replace the text "IfNotCurrentVersion" with a variable like so:

![image](https://user-images.githubusercontent.com/38642825/49607972-15558100-f95d-11e8-8905-23db09fdb7e5.png)

The step reverts back to "deploy every time"

![image](https://user-images.githubusercontent.com/38642825/49608002-2c946e80-f95d-11e8-8be9-d62bf70afc86.png)

When doing a deployment, it does the "deploy every time" as well.  It completely ignores the variable and just does the default.

## What I expected to happen

The step would use the variable and not default back to "deploy every time"

## Affected versions

**Octopus Server:** 2018.9.7

## Workarounds

Possible to make use of output variables and run conditions instead.  

## Links

Private link: https://secure.helpscout.net/conversation/725635860/36409?folderId=557077

**Comment by NickJosevski** [comment]
@OctopusBob I was unable to reproduce the deployment side problem of this. I responded to the customer, and I have my sample here, when you get a chance can you see how my setup differs from yours to work out if I missed something: https://master.octopushq.com/app#/projects/issue-5151-parent/releases/0.0.3/deployments/Deployments-12381?activeTab=taskLog

**Comment by droyad** [comment]
Related to #4772?

**Comment by droyad** [comment]
I could not reproduce the wrong deployment behaviour either, except that if the variable was invalid it acts like `DeployAlways`

The UI does show the wrong thing.

**Comment by OctopusBob** [comment]
Probably has been fixed since I filed it back then.  I've only heard about this issue once.  Might be worth doing a quick UI fix in the future, but it isn't super high priority.

**Comment by jjanuszkiewicz** [comment]
Hi, an Octopus Deploy client here. The UI fix would be really welcome, as currently it is a lot of unnecessary clicking to verify if the condition is set up correctly via variable binding (i.e. you can't see it at a glance so you have to click on it). Quite a pain for large numbers of projects and/or steps.

**Comment by matt-rauch** [comment]
Still doesn't work with v2020.5.6. I tried to use the following binding:
```
#{if Deployment.Force}
  Always
#{else}
  IfNotCurrentVersion
#{/if}
```
